#!/bin/sh
set -eu

cd "$(git rev-parse --show-toplevel)"

echo "Checking code style..."
./vendor/bin/pint --test --dirty

echo "Running PHPStan..."
./vendor/bin/phpstan analyse --memory-limit=2G --no-progress
